TITEL = "Praktische Projekte im Informatikstudium: Meistern der Komplexität"
CONTENT = (
    "# 1. Herausforderungen bei der Projektarbeit:\n"
    "Komplexe Anforderungen: Projekte können komplexe "
    "Anforderungen haben, die sorgfältige Analyse und Planung erfordern. Zeitdruck: Der Zeitrahmen für Projekte ist oft "
    "begrenzt, was zusätzlichen Druck auf die Studierenden ausüben kann. Zusammenarbeit: In Teamprojekten müssen "
    "Studierende effektiv zusammenarbeiten, was Kommunikation und Koordination erfordert.\n"
    "# 2. Lernmöglichkeiten durch Projekte:\n"
    "Praktische Anwendung: Projekte bieten die Möglichkeit, theoretisches Wissen in praktische Fähigkeiten umzusetzen. "
    "Problemlösung: Die Komplexität von Projekten schärft die Fähigkeiten zur Problemlösung und kreativen Denkens."
    "Zusätzliche Fähigkeiten: Teamarbeit, Zeitmanagement und Kommunikation sind zusätzliche Fähigkeiten, die durch"
    "Projektarbeit verbessert werden können.\n"
    "# 3. Blick auf die Zukunft:\n"
    "Portfolio-Aufbau: Erfolgreich abgeschlossene Projekte können zu einem beeindruckenden Portfolio beitragen, "
    "das bei zukünftigen Arbeitgebern Eindruck hinterlässt. Branchenrelevanz: Projekte können dazu beitragen,"
    "branchenspezifische Kenntnisse zu erwerben und die eigene Position auf dem Arbeitsmarkt zu stärken.\n")
