TITEL = "Informatikstudium: Die Kunst der Spezialisierung"

CONTENT = ("# 1. Künstliche Intelligenz (KI):\n"
           "Kernbereiche: KI ist ein dynamisches Feld, das maschinelles Lernen, neuronale Netzwerke, Robotik und mehr "
           "umfasst."
           "Anwendungen: Die Spezialisierung in KI ermöglicht es Studierenden, Technologien für Spracherkennung, "
           "Bildverarbeitung, autonome Systeme und fortschrittliche Datenanalysen zu entwickeln."
           "Berufsaussichten: Absolventen mit einer Spezialisierung in KI sind gefragt in Bereichen wie der "
           "Entwicklung"
           " von KI-Systemen, Datenanalyse und Forschung.\n"
           "# 2. Softwareentwicklung:\n"
           "Programmiersprachen: Diese Spezialisierung konzentriert sich auf die Kunst der Softwareentwicklung, wobei"
           " Programmiersprachen wie Java, Python, C++ und mehr im Mittelpunkt stehen."
           "Anwendungen: Studierende lernen, skalierbare Softwarelösungen zu entwerfen, zu implementieren und zu "
           "warten, und entwickeln Fähigkeiten in der Softwarearchitektur."
           "Berufsaussichten: Softwareentwickler sind in nahezu allen Branchen gefragt und können in der "
           "Anwendungsentwicklung, der Spieleentwicklung oder im Bereich der Unternehmenssoftware tätig werden.\n"
           "# 3. Datenwissenschaft:\n"
           "Datenanalyse: Diese Spezialisierung dreht sich um die Gewinnung von Erkenntnissen aus großen Datenmengen "
           "und umfasst statistische Analysen, maschinelles Lernen und Datenvisualisierung."
           "Anwendungen: Datenwissenschaftler arbeiten daran, Muster und Trends zu identifizieren, um fundierte "
           "Entscheidungen in Unternehmen zu ermöglichen."
           "Berufsaussichten: Die Nachfrage nach Datenwissenschaftlern steigt ständig, und Absolventen können in "
           "Bereichen wie Finanzwesen, Gesundheitswesen und E-Commerce tätig werden."
           "# 4. Internet of Things (IoT):\n"
           "Vernetzte Geräte: In dieser Spezialisierung lernen Studierende, vernetzte Systeme und IoT-Geräte zu "
           "entwickeln."
           "Anwendungen: IoT-Spezialisten sind in Branchen wie Smart Home, Gesundheitswesen und Industrie 4.0 gefragt."
           "Berufsaussichten: Mit der zunehmenden Vernetzung von Geräten wird die Expertise im Bereich IoT immer "
           "wichtiger.\n")
