TITEL = "Vielfalt in der Informatik: Entdecke die Welt der Studienrichtungen"
CONTENT = ("# Überblick über Informatikstudienrichtungen"
           "Die Informatik umfasst weit mehr als nur das Schreiben von Code. Studierende haben die Möglichkeit, "
           "sich auf verschiedene Fachgebiete zu spezialisieren, darunter Softwareentwicklung, Datenbankmanagement, "
           "Netzwerke, Sicherheit und vieles mehr. Diese Studienrichtungen bilden die Grundpfeiler für eine fundierte "
           "Ausbildung in der Informatik."
           "# Klassische Studienrichtungen"
           "Die klassischen Studienrichtungen bilden das Rückgrat der Informatik. Hier werden grundlegende "
           "Fähigkeiten in Bereichen"
           " wie Algorithmen, Datenstrukturen und Softwarearchitektur vermittelt. Die Studienrichtungen umfassen "
           "Softwareentwicklung, Datenbankmanagement, Netzwerke und Sicherheit, wobei jeder Bereich einzigartige "
           "Einblicke in die Welt der Informatik bietet."
           "# Spezialisierungen und neue Trends"
           "In einer sich ständig weiterentwickelnden digitalen Welt entstehen ständig neue Studienrichtungen und "
           "Trends."
           "Künstliche Intelligenz, maschinelles Lernen, Datenwissenschaft, Cybersecurity und Blockchain-Technologie "
           "sind nur einige Beispiele. Diese Studienrichtungen spiegeln die aktuellen Anforderungen der Branche wider "
           "und bieten spannende Möglichkeiten für zukünftige Karrieren."
           "# Berufsaussichten und Anwendungsgebiete"
           "Die Informatik eröffnet eine Vielzahl von Karrierewegen in verschiedenen Branchen. Absolventen können in "
           "der"
           "Softwareentwicklung, im Gesundheitswesen, in der Finanzbranche und vielen anderen Bereichen tätig werden. "
           "Schließlich werfen wir einen kurzen Blick in die Zukunft. Wie wird sich die Informatiklandschaft "
           "weiterentwickeln?"
           "Welche neuen Studienrichtungen könnten entstehen? Ein Blick auf kommende Trends kann angehenden "
           "Studierenden"
           " helfen, gut informierte Entscheidungen zu treffen. ")
