TITEL = "Die Kunst des Zeitmanagements im Informatikstudium: Strategien zur Bewältigung der Arbeitsbelastung"

CONTENT = (
    "# 1. Erstellung eines Zeitplans:\n"
    "Nutzen eines Kalenders: Verwenden Sie einen digitalen Kalender oder eine Planung-App, um Vorlesungen, Prüfungen, "
    "und Projektmeilensteine festzuhalten. Priorisierung: Ordnen Sie Aufgaben nach Dringlichkeit und Wichtigkeit, "
    "um den Fokus auf Schlüsselaufgaben zu legen.\n"
    "# 2. Realistische Ziele setzen:\n"
    "Teilziele definieren: Zerlegen Sie größere Aufgaben in kleinere, leichter zu bewältigende Schritte. Setzen Sie "
    "sich"
    "realistische Ziele für jeden Tag. Pufferzeiten einplanen: Berücksichtigen Sie unvorhergesehene Verzögerungen oder "
    "zusätzliche Zeit, die für komplexe Aufgaben benötigt wird.\n"
    "# 3. Effektive Nutzung von Lernzeiten:\n"
    "Aktives Lernen: Vermeiden Sie passives Lesen. Nutzen Sie aktive Lernmethoden wie Zusammenfassungen schreiben, "
    "Quizfragen erstellen oder Diskussionen führen. Pomodoro-Technik: Arbeiten Sie in Intervallen von etwa 25 Minuten "
    "konzentriert, gefolgt von einer kurzen Pause. Dies kann die Produktivität steigern.\n"
    "# 4. Delegation und Zusammenarbeit:\n"
    "Teilen von Aufgaben: Bei Gruppenprojekten ist die klare Verteilung von Aufgaben unter den Teammitgliedern "
    "entscheidend. Gemeinsame Lerngruppen: Zusammenarbeit mit Kommilitonen ermöglicht den Austausch von Wissen und kann"
    "das Verständnis vertiefen.\n")
